networks:
  microservices-net:
    driver: bridge

volumes:
  consul-data:
  postgres-data:
  rabbitmq-data:

services:
  consul:
    image: consul:1.15
    container_name: consul
    restart: always
    ports:
      - "8500:8500"
    command: agent -server -bootstrap-expect=1 -node=consul-server -client=0.0.0.0 -ui -bind=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - consul-data:/consul/data
    networks:
      - microservices-net

  postgresql:
    image: postgres:16-alpine
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: ingest-service-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d ingest-service-db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-net

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: appuser
      RABBITMQ_DEFAULT_PASS: cfrPkyUHpLExTNw
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s
    ulimits:
      nofile: 65536
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - microservices-net

  config-service:
    build: ./config-service
    container_name: config-service
    restart: on-failure
    ports:
      - "8888:8888"
    environment:
      - CONSUL_HOST=consul
      - CONFIG_LOCATION=/app/configs
    depends_on:
      consul:
        condition: service_healthy
    volumes:
      - ./configs:/app/configs
    networks:
      - microservices-net

  ingest-service:
    build: ./ingest-service
    container_name: ingest-service
    restart: on-failure
    environment:
      - CONSUL_HOST=consul
      - CONFIG_SERVER_HOST=config-service
      - INGEST_SERVICE_PORT=8080

      - DATASOURCE_URL=postgresql
      - DATASOURCE_USERNAME=postgres_user
      - DATASOURCE_PASSWORD=postgres_password

      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=appuser
      - RABBITMQ_PASSWORD=cfrPkyUHpLExTNw
      - RABBITMQ_QUEUE_NAME=queue

      - cloud.aws.bucket.name=${S3_BUCKET_NAME}
      - cloud.aws.credentials.access-key=${S3_ACCESS_KEY}
      - cloud.aws.credentials.secret-key=${S3_SECRET_KEY}
      - cloud.aws.region.static=${AWS_REGION}
    depends_on:
      postgresql:
        condition: service_healthy
      config-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - microservices-net

  ocr-nlp-service:
    build: ./ocr-nlp-service
    container_name: ocr-nlp-service
    restart: on-failure
    environment:
      - CONSUL_HOST=consul
      - CONFIG_SERVER_HOST=config-service
      - OCR_NLP_SERVICE_PORT=8080

      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=appuser
      - RABBITMQ_PASSWORD=cfrPkyUHpLExTNw
      - RABBITMQ_QUEUE_NAME=queue
    depends_on:
      ingest-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      config-service:
        condition: service_started
    networks:
      - microservices-net

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      ocr-nlp-service:
        condition: service_started
      ingest-service:
        condition: service_started
    environment:
      - CONSUL_HOST=consul
      - CONFIG_SERVER_HOST=config-service
    networks:
      - microservices-net