spring:
  application:
    name: ingest-service

  config:
    import: "configserver:http://${CONFIG_SERVER_HOST:localhost}:8888"

  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 15s
        health-check-timeout: 5s
        health-check-critical-timeout: 30s
        prefer-ip-address: false
        hostname: ingest-service
        register: true