spring:
  application:
    name: hello-service

  config:
    import: "configserver:http://${CONFIG_SERVER_HOST:localhost}:8888"

  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: true