server:
  port: ${INGEST_SERVICE_PORT:0}

spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_URL:localhost}:5432/ingest-service-db
    username: ${DATASOURCE_USERNAME:postgres_user}
    password: ${DATASOURCE_PASSWORD:postgres_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update