server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active:
      - native
  cloud:
    config:
      server:
        native:
          search-locations: file:${CONFIG_LOCATION:./configs}

    consul:
      host: ${CONSUL_HOST:localhost}
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include:
          - "health"